fos_elastica:
    indexes:
        bitbag_vue_storefront_catalog_attribute:
            index_name: "%env(ELASTICSEARCH_INDEX)%_attribute"
            
            properties:
                enabled: ~
                id: { type: long }
                attribute_id: { type: long }
                options:
                    type: nested
                    properties:
                        value: { type: text }
            persistence:
                driver: orm
                model: "%sylius.model.product_option.class%"
                identifier: documentId
                model_to_elastica_transformer:
                    service: bitbag_sylius_vue_storefront_plugin.transformer.attribute
                provider: ~
                listener:
                    logger: true
                    defer: true
